import Config

# Configure your database
#
# DB_HOSTNAME defaults to "localhost" (PG on the host) — set it to the
# compose service name "postgres" when the app runs inside a container
# (docker-compose.yml / scripts/dev.*).
# Business tables live in schema `chat_v2` (spec §3); `public.users`
# (profiles) is queried with an explicit `prefix: "public"` on the same
# Repo/connection (spec §4: reads hit one PG instance).
# DB_* env overrides exist for the cutover tools (issue #4): pointing dev at
# the live archive DB (e.g. DB_HOSTNAME=192.168.10.13 DB_USERNAME=dzmm
# DB_PASSWORD=... DB_NAME=dzmm) lets `mix lilium_chat.import/export` run
# against production data without a separate env config.
config :lilium_chat, LiliumChat.Repo,
  username: System.get_env("DB_USERNAME") || "chat",
  password: System.get_env("DB_PASSWORD") || "chat",
  hostname: System.get_env("DB_HOSTNAME") || "localhost",
  port: String.to_integer(System.get_env("DB_PORT") || "5432"),
  database: System.get_env("DB_NAME") || "lilium_chat_dev",
  prefix: "chat_v2",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# ToolBear JWT secret (spec §6.1). Dev default only — prod reads JWT_SECRET.
config :lilium_chat, :jwt,
  secret: System.get_env("JWT_SECRET") || "dev-only-jwt-secret-not-for-prod"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Bind all interfaces by default so the app is reachable through podman
# port forwarding (host:4000 → container eth0). Set HTTP_BIND_IP=127.0.0.1
# to restrict to loopback when running the app directly on the host.
bind_ip =
  case System.get_env("HTTP_BIND_IP") do
    "127.0.0.1" -> {127, 0, 0, 1}
    _ -> {0, 0, 0, 0}
  end

config :lilium_chat, LiliumChatWeb.Endpoint,
  http: [ip: bind_ip, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "CtRiR0v4qV9JmK2FVRT2eIqzJcFyD9o3Ntc9317x19LSjP1VjMZ0pdhML9biGdCp",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :lilium_chat, dev_routes: true

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
